###
GET http://127.0.0.1:8000/api/v1/department/CCS
Accept: application/json
Authorization: Bearer 405|ZDCD3IHIKYbhhyMQA9PEQrMbMc84ex3HMSQLZVTMba9a49ae

###
POST http://127.0.0.1:8000/api/v1/department
content-type: application/json
Authorization: Bearer 405|ZDCD3IHIKYbhhyMQA9PEQrMbMc84ex3HMSQLZVTMba9a49ae
Accept: application/json

{
    "department_code": "CBA",
    "department_name": "College Business Administration"
}

###
PUT http://127.0.0.1:8000/api/v1/department/CN
content-type: application/json
Authorization: Bearer 36|kH6uYerbm9qvDialJ1xd1rICrCH1OgOH3YQqIiIHd012c76a
Accept: application/json

{
    "department_code" : "CNR",
    "department_name" : "College of Nursing"
}

###
DELETE http://127.0.0.1:8000/api/v1/department/CN
Accept: application/json
Authorization: Bearer 30|gTnkA28MR3c0kTBCxPQlnusresYWJNzJzSNCgJrH189619c6