###
GET http://127.0.0.1:8000/api/v1/department
Accept: application/json
Authorization: Bearer 1|g3fZFXDy9H0syf4NhUKZpmGtzAFi1Dy0MytPFH5P32cc1df7

###
POST http://127.0.0.1:8000/api/v1/department
content-type: application/json
Authorization: Bearer 1|F1qPsxzHNkR6zzI2Qt9YCicFWGYzSe6jygRcv4qWf5bc2daf
Accept: application/json

{
    "department_code": "CBA",
    "department_name": "College Business Administration"
}

###
PUT http://127.0.0.1:8000/api/v1/department/CN
content-type: application/json
Authorization: Bearer 36|kH6uYerbm9qvDialJ1xd1rICrCH1OgOH3YQqIiIHd012c76a
Accept: application/json

{
    "department_code" : "CNR",
    "department_name" : "College of Nursing"
}

###
DELETE http://127.0.0.1:8000/api/v1/department/CN
Accept: application/json
Authorization: Bearer 30|gTnkA28MR3c0kTBCxPQlnusresYWJNzJzSNCgJrH189619c6