###
GET http://127.0.0.1:8000/api/v1/program-outcome/1
Authorization: Bearer 1|FtkcTl3Tnjqc06pCco80ZkNZaLBYmq54wNyzu8rC704da551
Accept: application/json

###
GET http://127.0.0.1:8000/api/v1/program-outcome-progCode/BSIT
Authorization: Bearer 7|MezYetxmKfNWfXQwcCTO0r9kziLie7SHeSAH2she8ff33957
Accept: application/json

###
POST http://127.0.0.1:8000/api/v1/program-outcome
Authorization: Bearer 7|MezYetxmKfNWfXQwcCTO0r9kziLie7SHeSAH2she8ff33957
content-type: application/json
Accept: application/json

{
    "po_desc" : "First Second Third Outcomes BSCS",
    "program_id": 2,
    "seq_num" : 3
}

###
PUT http://127.0.0.1:8000/api/v1/program-outcome/1
Authorization: Bearer 1|FtkcTl3Tnjqc06pCco80ZkNZaLBYmq54wNyzu8rC704da551
content-type: application/json
Accept: application/json

{
    "po_desc": "This is the first Program Outcomes",
    "program_id": 1,
    "seq_num" : 1
}

###
DELETE http://127.0.0.1:8000/api/v1/program-outcome/1
Authorization: Bearer 6|iNpDobU0SXjFpQf5mBh617lmFtD58v0mm6cuegzh8c8344ee
Accept: application/json