    ###
GET http://127.0.0.1:8000/api/v1/program 
Accept: application/json
Authorization: Bearer 405|ZDCD3IHIKYbhhyMQA9PEQrMbMc84ex3HMSQLZVTMba9a49ae

###
POST http://127.0.0.1:8000/api/v1/program
content-type: application/json
Authorization: Bearer 427|uCJiCLDXYWVpBtCu0PqmOpVkXEg3HkN7u6ktj4We012b8e28
Accept: application/json

{
    "program_code" : "BSCE",
    "program_description" : "Bachelor of Science in Computer Engineeering",
    "department_id" : 1
}

###
PUT http://127.0.0.1:8000/api/v1/program/
content-type: application/jsons
Authorization: Bearer 37|5szRufJt119PDMp7RMqPKPHFEEJ2z6S0J5HGoroR8674f8fe
Accept: application/json

{
    "program_code" : "BSIT",
    "program_description" : "Bachelor of Information Technology",
    "department_id" : 1
}

###
DELETE http://127.0.0.1:8000/api/v1/program/BSCE
Accept: application/json
Authorization: Bearer 427|uCJiCLDXYWVpBtCu0PqmOpVkXEg3HkN7u6ktj4We012b8e28